### ISSUE TITLE
createWriteStream

### ISSUE THREAD

**Issue by cultulhul** [cravler/fs.promises#1]
using createWriteStream is causing an err and the on err eventhandler is not firing

**Comment by cravler** [comment]
This method is not a part of `fs.promises`, use `require('fs').createWriteStream`.
https://github.com/nodejs/node/blob/master/lib/internal/fs/promises.js#L492

**Comment by cultulhul** [comment]
yeah just noticed when i viewed the code, wanted to not have to require fs multiple times, i found [https://github.com/75lb/fs-then-native/blob/master/fs-then-native.js](url)
that uses Object.assign and then over writes some of the properties with promises

**Comment by cravler** [comment]
it's just a polyfill and you need `require('fs.promises');` only once in main JS file

``` js
// main.js
require('fs.promises');
require('./app');

// app.js
const fs = require('fs');
require('fs').createWriteStream
fs.promises.readFile
```
